---
- name: Create the '{{ hyper_v_virtual_switch_name }}' Switch
  ansible.windows.win_powershell:
    script: |
      Import-Module Hyper-V;
      $Ansible.Changed = $false
      $sw = Get-VMSwitch -Name "{{ hyper_v_virtual_switch_name }}" -ErrorAction Ignore
      if ($sw -eq $null){
          $Ansible.Changed = $true  
          try {
            New-VMSwitch -Name "{{ hyper_v_virtual_switch_name }}" -NetAdapterName "{{ hyper_v_physical_network_adapter_name }}" -ErrorAction Stop
          } catch {
            $Ansible.Changed = $false
            $Ansible.Failed = $true
            return "Failed to create new switch: $_"
          }
      } else {
          $currentNetAdapterName = Get-NetAdapter -InterfaceDescription $sw.NetAdapterInterfaceDescription
          if ($currentNetAdapterName.Name -ine "{{ hyper_v_physical_network_adapter_name }}"){
              $Ansible.Changed = $true  
              $sw | Set-VMSwitch -NetAdapterName "{{ hyper_v_physical_network_adapter_name }}"
          }
      }

      $rvHashtable = @{
        'Network Adapter Name' = '{{ hyper_v_physical_network_adapter_name }}'
        'Switch Name' = '{{ hyper_v_virtual_switch_name }}'
      }

      $rv = New-Object -TypeName PSObject -Property $rvHashtable

      return $rv


  register: pwsh_output
  async: 30
  poll: 3
  
- name: Output PWSH
  debug:
    var: pwsh_output
  delegate_to: localhost
