--- 
- name: Include vm env var
  include_vars:
    file: "template_VMs.yml"

- name: Create VMs
  win_hyperv_guest:
    name: "{{item.name}}"
    generation: 2
    cpu: "{{item.cpu}}"
    memory: "{{item.memory}}"
    network_switch: "{{item.network_switch}}"
    state: present
  with_items: "{{ vms }}"
  register: new_vms    