---
- name: Add new Linux hosts to inventory
  ansible.builtin.add_host:
    hostname: '{{ current_ip }}'
    ansible_host: '{{ current_ip }}'
    ansible_user: ansible
    ansible_password: Password1!
    ansible_port: 22
    ansible_connection: ssh
  
- name: Wait for {{ item.value.os_type }} system ({{ current_ip }}) to become reachable over WinRM or SSH
  ansible.builtin.wait_for_connection:
    timeout: "{{ wait_for_timeout }}"
  delegate_to: '{{ current_ip }}'

- name: Update apt repo and cache on all Debian/Ubuntu boxes
  become: true
  apt: 
    update_cache: yes 
    force_apt_get: yes 
    cache_valid_time: 3600 
  delegate_to: '{{ current_ip }}'

- name: Upgrade all packages on server
  become: true
  apt: 
    upgrade: dist
    force_apt_get: yes
  delegate_to: '{{ current_ip }}'

- name: Check if a reboot is needed for Debian and Ubuntu boxes
  become: true
  register: reboot_required_file
  stat: 
    path: /var/run/reboot-required 
    get_md5: no
  delegate_to: '{{ current_ip }}'

- name: Reboot the Debian or Ubuntu server
  become: true
  reboot:
    msg: "Reboot initiated by Ansible due to kernel updates"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  delegate_to: '{{ current_ip }}'
  when: reboot_required_file.stat.exists

- name: delete authorized_keys
  become: true
  delegate_to: '{{ current_ip }}'
  file: 
    path: /root/.ssh/authorized_keys
    state: absent

- name: delete bash history
  become: true
  delegate_to: '{{ current_ip }}'
  file: 
    path: /root/.bash_history
    state: absent
  
- name: delete old ssh host keys
  become: true
  delegate_to: '{{ current_ip }}'
  file: 
    path: /etc/ssh/ssh_host_*
    state: absent  

- name: generate new ssh host keys
  become: true
  delegate_to: '{{ current_ip }}'
  command: ssh-keygen -A

- name: stop for final configuration
  become: true
  delegate_to: '{{ current_ip }}'
  community.general.shutdown: